import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, Section, List } from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy — FindTao",
  description: "How FindTao handles your data: what's stored locally, what syncs to your account, and the third parties involved.",
};

const CONTACT_EMAIL = "fuzion.viziion@gmail.com";
const OPERATOR = "FindTao";

export default function PrivacyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      updated="July 9, 2026"
      intro={
        <>
          <p>
            {OPERATOR} (&ldquo;we&rdquo;, &ldquo;us&rdquo;) is a discovery and planning tool for
            shopping on Chinese marketplaces (Taobao, Weidian, 1688, Xianyu) and handing off to a
            third-party shopping agent. We do not sell products or process payments. This policy
            explains what we collect, why, and who else is involved.
          </p>
          <p>
            The short version: <strong className="text-mist-100">you can use almost the entire app
            without an account</strong>, and when you do, your data stays in your own browser. An
            account only exists to sync that data across your devices.
          </p>
        </>
      }
    >
      <Section heading="1. Data stored only on your device">
        <p>
          By default, {OPERATOR} runs in &ldquo;local mode.&rdquo; The following is written to your
          browser&rsquo;s <code className="text-mist-200">localStorage</code> and never leaves your
          device unless you create an account:
        </p>
        <List
          items={[
            "Your preferences (display currency, preferred agent, referral codes, theme, card density).",
            "Your wishlist, cart, and hauls (group orders and budgets).",
            "Stores you follow or favorite, and any stores you add yourself.",
            "Package tracking numbers you enter.",
            "Your body measurements and fit preference, used by the AI size Advisor.",
          ]}
        />
        <p>
          Clearing your browser storage for this site permanently deletes all of the above. In local
          mode we hold none of it on our servers.
        </p>
      </Section>

      <Section heading="2. Data tied to an account (optional)">
        <p>
          If you create an account, we use <strong className="text-mist-100">Supabase</strong> (our
          authentication and database provider) to store:
        </p>
        <List
          items={[
            "Your email address and a username you choose, for sign-in and to identify your account.",
            "A single synced copy of your app state (the same preferences, cart, hauls, followed stores, tracking numbers, and body measurements described above), so it follows you across devices.",
            "Role tags on your profile (e.g. whether you are an administrator).",
          ]}
        />
        <p>
          We authenticate by email/password or a &ldquo;magic link&rdquo; sent to your email. We do
          not see or store your password in readable form — authentication is handled by Supabase.
        </p>
        <p className="text-mist-400">
          Note on body measurements: if you use the size Advisor while signed in, your measurements
          are part of the synced state and are stored in your account. We use them only to generate
          size recommendations for you. We never sell them or use them for advertising.
        </p>
      </Section>

      <Section heading="3. The AI size Advisor">
        <p>
          When you ask the Advisor to read a size chart, the app fetches the seller&rsquo;s
          publicly-posted chart photo from the store&rsquo;s own page and sends that image to{" "}
          <strong className="text-mist-100">Anthropic</strong> (the AI provider) for analysis. You do
          not upload anything yourself, and the image is a public product photo, not your personal
          data. Your body measurements are compared against the chart <em>on our server</em> and are
          not sent to the AI provider.
        </p>
      </Section>

      <Section heading="4. Information collected automatically">
        <List
          items={[
            "IP address: used transiently to rate-limit our scraping and AI endpoints so they aren't abused. It is held in memory as a short-lived counter and is not part of a long-term profile of you.",
            "Standard server logs generated by our hosting provider, which may include IP address, request time, and user-agent for security and reliability.",
            "We do not use advertising cookies or third-party analytics/tracking pixels. Sign-in uses tokens stored in your browser, not tracking cookies.",
          ]}
        />
      </Section>

      <Section heading="5. Third parties we rely on">
        <p>We share the minimum necessary with these service providers (&ldquo;sub-processors&rdquo;):</p>
        <List
          items={[
            <><strong className="text-mist-100">Supabase</strong> — account authentication and database (stores your email, username, and synced app state).</>,
            <><strong className="text-mist-100">Anthropic</strong> — AI reading of publicly-posted size-chart photos (no personal data sent).</>,
            <>Our <strong className="text-mist-100">hosting provider</strong> — serves the app and generates server logs.</>,
            <><strong className="text-mist-100">open.er-api.com</strong> — live currency exchange rates (no personal data sent).</>,
            <><strong className="text-mist-100">Yupoo</strong> and <strong className="text-mist-100">Weidian</strong> — we fetch public store/album pages to show you listings; we send them no information about you.</>,
          ]}
        />
        <p>
          When you click through to a shopping agent (Kakobuy, Superbuy, CNFans, etc.) or a tracking
          service (17TRACK), you leave {OPERATOR} and that site&rsquo;s own privacy policy governs
          what happens next. Those outbound links may include our referral code; see our{" "}
          <Link href="/terms" className="text-neon-300 underline">Terms</Link> for the affiliate
          disclosure. Adding a referral code does not change the price you pay.
        </p>
      </Section>

      <Section heading="6. International data transfers">
        <p>
          {OPERATOR} is available worldwide. The providers we rely on (such as Supabase, Anthropic,
          and our hosting provider) may store or process data in the United States or other countries
          whose data-protection laws differ from those where you live. Where we transfer personal data
          out of the EEA or the UK, we rely on appropriate safeguards, such as the European
          Commission&rsquo;s Standard Contractual Clauses. By creating an account and syncing your
          data, you understand that it may be processed in these countries.
        </p>
      </Section>

      <Section heading="7. Your choices and rights">
        <List
          items={[
            "Access / delete local data: clear this site's browser storage at any time to erase everything held in local mode.",
            <>Delete your account: contact us at <span className="text-mist-100">{CONTACT_EMAIL}</span> and we will delete your account and its synced data.</>,
            "You can use the app fully without ever creating an account.",
          ]}
        />
        <p>
          Depending on where you live, you may have additional rights (see the next two sections).
        </p>
      </Section>

      <Section heading="8. If you are in the EEA or UK (GDPR)">
        <p>
          Our legal bases are: <strong className="text-mist-100">consent</strong> (creating an
          account and syncing your data, including body measurements), and our{" "}
          <strong className="text-mist-100">legitimate interests</strong> (keeping the service secure
          and functional, e.g. rate-limiting by IP). You have the right to access, correct, delete,
          restrict, or port your data, and to withdraw consent at any time by deleting your account.
          You may also lodge a complaint with your local data-protection authority.
        </p>
      </Section>

      <Section heading="9. If you are in California (CCPA/CPRA)">
        <p>
          We do not sell or &ldquo;share&rdquo; your personal information for cross-context behavioral
          advertising. You have the right to know what we collect, to request deletion, and not to be
          discriminated against for exercising these rights. To make a request, contact us at{" "}
          <span className="text-mist-100">{CONTACT_EMAIL}</span>.
        </p>
      </Section>

      <Section heading="10. Data retention & security">
        <p>
          Account data is kept until you delete your account. Local-mode data lives only in your
          browser until you clear it. We use access controls (database row-level security so each
          account can only read its own synced state) and encrypted transport (HTTPS). No method of
          storage or transmission is perfectly secure, and we cannot guarantee absolute security.
        </p>
      </Section>

      <Section heading="11. Children">
        <p>
          {OPERATOR} is not directed to children under 13 (or the minimum age in your country), and
          we do not knowingly collect their data. If you believe a child has given us personal
          information, contact us and we will delete it.
        </p>
      </Section>

      <Section heading="12. Changes & contact">
        <p>
          We may update this policy; we&rsquo;ll change the &ldquo;last updated&rdquo; date above when
          we do. Questions or requests: <span className="text-mist-100">{CONTACT_EMAIL}</span>.
        </p>
      </Section>
    </LegalPage>
  );
}
